export interface TiposVias {
  // RESPUESTA DEL SERVER LISTADO GENERAL
  INTTVICODIGO? : string; // VALOR COMPARTIDO PARA LISTADO Y CONSULTAS
  VCHTVIDESCRIPCION? : string;

  // CONSULTA BASADA EN PARAMETROS
  VCHVIACODIGO? : string;
  VCHVIADESCRIPCION? : string;
}
