export interface TiposHabilitaciones {
  // CONSULTA BASADA EN PARAMETROS
  CHRCURCODIGO? : string;
  // RESPUESTA DEL SERVER LISTADO GENEREAL
  INTTCUCODIGO? : string; //VALOR COMPARTIDO PARA LISTADO Y CONSULTAS
  CHRCURESTADO? : string;
  VCHCURDESCRIPCION1? : string;
  VCHTCUDESCRIPCION? : string;
}
